---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata: "@ignore@"
  spec: "@ignore@"

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  spec:
    replicas: 1
    revisionHistoryLimit: 8